[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/reset-password"
  to = "/.netlify/functions/auth"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"